const { sidebarConfig } = require("vuepress-theme-hope");

module.exports = sidebarConfig([
    "Kotlin 使用 Gradle",
    "Kotlin 接口",
    "Kotlin 对象",
    "Kotlin 基础",
    "Kotlin Android Extension",
    "Kotlin 基本类型",
    "Java to Kotlin",
    "Kotlin 类基础",
    "Kotlin 控制流程",
    "Kotlin 空安全",
    "Kotlin 类属性和域",
    "Kotlin 函数",
    "Kotlin 调用 Java 代码",
    "Kotlin 异常",
    "Kotlin 数据类",
    "Kotlin 范围",
    "Kotlin 可见性修饰符",
    "Kotlin 内联函数",
    "Kotlin 委托模式",
    "Kotlin 泛型",
    "Kotlin 内部类",
    "Kotlin 高阶函数和 Lambda",
    "Kotlin `this` 表达式",
    "Kotlin 类型检查和造型",
    "Kotlin 枚举类",
    "Kotlin 委托属性",
    "Kotlin 扩展类型",
    "Kotlin 集合",
    "Kotlin 相等性",
    "Kotlin lateinit vs lazy",
    "Kotlin 操作符重载",
    "Kotlin Android Getting Started",
    "Kotlin Scoping 函数",
]);