# This is a basic workflow to help you get started with Actions
name: Deploy to Github Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the source branch
  push:
    branches: 
      - source

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-gh-pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: CheckOut
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
          ref: source

      # Cache
      - uses: actions/cache@v2.1.7
        id: node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Install Deps
      - name: Install Deps
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      
      # Build blog
      - name: Build 
        run: yarn run docs:build

      # Deploy
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: dist
